### ISSUE TITLE
Please add versioning to the provider

### ISSUE THREAD

**Issue by chrisvdg** [gig-tech/terraform-provider-ovc#1]
(⎈ |admin@meneja-qas-be:default)rgevaert@Rudys-Air:~/Vcs/terraform-provider-ovc/examples (simple-example)$ terraform providers -v
Terraform v0.11.11
+ provider.ovc (unversioned)

Original issue: https://git.gig.tech/nubera/terraform-provider-ovc/issues/26

**Comment by katia-e** [comment]
Updated README to version binary

**Comment by katia-e** [comment]
To produces versioned plugin binaries create release/push tags

**Comment by chrisvdg** [comment]
This issue can be closed when v1.0.0 tag is pushed
