### ISSUE TITLE
Can't add more then 1 disk at once, with count statement

### ISSUE THREAD

**Issue by chrisvdg** [gig-tech/terraform-provider-ovc#2]
when doing this:
resource "ovc_disk" "disk" {
count = 5
...
this is not working
you need to run "apply" 4 times to get all disks

Original issue: https://git.gig.tech/nubera/terraform-provider-ovc/issues/25

**Comment by chrisvdg** [comment]
Serialize actions in the provider

Original comment: https://git.gig.tech/nubera/terraform-provider-ovc/issues/25#note_220437

**Comment by katia-e** [comment]
Currently provider seems to work as expected. During the test managed to add 5 disks in one go.

**Comment by chrisvdg** [comment]
Document this is not how we want multiple disks to be defined as because of this we can't update/remove/... a specific drive.
Maybe throw an error if `count > 1`

**Comment by chrisvdg** [comment]
This will be added as an example

**Comment by chrisvdg** [comment]
Added example in https://github.com/gig-tech/terraform-provider-ovc/pull/36
