### ISSUE TITLE
add mode and type to cloudspace

### ISSUE THREAD

**Issue by hteibler** [gig-tech/terraform-provider-ovc#54]
add new features

 mode and type to cloudspace object

**Comment by katia-e** [comment]
**notes**:
fields were added with [this commit](https://github.com/gig-tech/ovc-sdk-go/pull/20/commits/7796eaec57310446f3f27561a48c4378558c811a)

Still to do:
1. Check if switching from ROS to VGW is possible via API, if yes, support from terraform
2. Error if trying to change type/mode after creation

**Comment by hteibler** [comment]
and also to
terraform-provider-ovc/ovc/resource_ovc_cloudspace.go
terraform-provider-ovc/ovc/data_source_ovc_cloudspace.go

**Comment by katia-e** [comment]
Added in https://github.com/gig-tech/terraform-provider-ovc/pull/60

**Comment by carlossz01** [comment]
Hello Katia I have one doubt. is this type the one that is required to create the cloudspace from terraform using RouterOS? is it released now in your latest provider? 

This is my current script from main.tf

```terraform
resource "ovc_cloudspace" "cloudspace" {
  account = "${var.account_name}"
  name = "${var.cloudspace_name}"
   resource_limits = {
     max_memory_capacity = 4
     max_disk_capacity = 100
     max_cpu_capacity = 4
     max_num_public_ip = 1
     max_network_peer_transfer = 4
   }
}

Can i add something like type = routeros at the resource_limits fields?

Thanks!!!

**Comment by katia-e** [comment]
Carlos, you can indeed add type, but not under `resource_limits`. Please see sample the config
``` shell
resource "ovc_cloudspace" "cloudspace" {
  account = "${var.account_name}"
  name = "${var.cloudspace_name}"
  type = "routeros"
   resource_limits = {
     max_memory_capacity = 4
     max_disk_capacity = 100
     max_cpu_capacity = 4
     max_num_public_ip = 1
     max_network_peer_transfer = 4
   }
}
```
