### ISSUE TITLE
network_id is not idempotant 

### ISSUE THREAD

**Issue by hteibler** [gig-tech/terraform-provider-ovc#59]
see example:

resource "ovc_machine" "machine1" {
  cloudspace_id = "${ovc_cloudspace.cs1.id}"
  image_id = 1
  memory = 2024
  vcpus = 2
  disksize = 10
  name = "VM in CS1"
  description = "na"
  act_as_default_gateway = true
  interfaces = {
    network_id = 1
  }
}

on each apply you get:

Terraform will perform the following actions:

  ~ ovc_machine.machine1                                                                                                                                                                                   interfaces.0.network_id: "0" => "1"            

and system is creating a new interface in the VM with a new IP!

**Comment by hteibler** [comment]
workaround:
don't specify network_id just do:
interfaces = { }

then you get:
      interfaces.#:            "1"
      interfaces.0.ip_address: <computed>
      interfaces.0.network_id: <computed>

problem:
same as with "resource_limits"
when you only define part of the  "struct" !!!

**Comment by katia-e** [comment]
This should work correctly from OpenvCloud 2.5.3.2.
