### ISSUE TITLE
Use refreshable JWT isof client_id & secret

### ISSUE THREAD

**Issue by chrisvdg** [gig-tech/terraform-provider-ovc#6]
It is wrong to ask the client_id & secret of a user. Its insecure for the user, because with this information the program is able to administer the users account in itsyou.online, while it only needs a way to authenticate itself to the api of OpenvCloud.

![](https://git.gig.tech/nubera/terraform-provider-ovc/uploads/d8d409d42e80c056528f225f2b6ffdee/image.png)

Original issue: https://git.gig.tech/nubera/terraform-provider-ovc/issues/21

**Comment by chrisvdg** [comment]
For backwards compatibility:
- Add the possibility to use JWT
- Log WARNING when using clientid and secret directly
- If provided both, crash


Original comment: https://git.gig.tech/nubera/terraform-provider-ovc/issues/21#note_220460

**Comment by chrisvdg** [comment]
Resolved in https://github.com/gig-tech/terraform-provider-ovc/pull/21

**Comment by rgevaert** [comment]
@chrisvdg 

Do still read the environment variables mentioned below? I would expect this to still work:
```
$ set | egrep 'ITS|TF_VAR'
ITSYOU_ONLINE_CLIENT_ID=xxxx
ITSYOU_ONLINE_CLIENT_SECRET=xxx
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: Error refreshing state: 1 error(s) occurred:

* provider.ovc: Failed to fetch JWT: Bad Request
```

**Comment by katia-e** [comment]
ITSYOU_ONLINE_CLIENT_SECRET, ITSYOU_ONLINE_CLIENT_SECRET will work if you remove `client_id` and `client_secret` variables not only from `main.tf`, but also from `variables.tf`. It asked for value, because `variables.tf` had the variables defined, but no default were not set for it.

**Comment by chrisvdg** [comment]
They are still used
https://github.com/gig-tech/terraform-provider-ovc/blob/master/ovc/provider.go#L22

Don't know what caused change in behavior, only thing that got added was the `client_jwt` and `ConflictWith` parameter was set to enforce either id/secret or jwt for authentication
https://github.com/gig-tech/terraform-provider-ovc/commit/89dd69c2a3b9df48e3a5e64fafd5b9c5e9d056be#diff-e016fea76f06ff10e69325d46570862aL19
