### ISSUE TITLE
boot disk handling

### ISSUE THREAD

**Issue by chrisvdg** [gig-tech/terraform-provider-ovc#7]
need to set IOPS for Bootdisk on creation
there is no possibility to update/resize the boot disk

Original issue: https://git.gig.tech/nubera/terraform-provider-ovc/issues/19

**Comment by chrisvdg** [comment]
Need to be able to resize / set iops to any disk.
Please also support the fine-graned iops settings

Original comment: https://git.gig.tech/nubera/terraform-provider-ovc/issues/19#note_220461

**Comment by chrisvdg** [comment]
Setting IOPS doesn't seem to be possible on creation, add a second call to update IOPS  if specified in the config.

**Comment by chrisvdg** [comment]
Resolved in https://github.com/gig-tech/terraform-provider-ovc/pull/35

**Comment by katia-e** [comment]
IOPS option works fine for managing boot disk.

Updating Boot Disk size doesn't work now, ones VM is creates changing `disksize` updates local terraform state, but does not update disk size on OVC
