### ISSUE TITLE
There is always a change with cloudspaces

### ISSUE THREAD

**Issue by chrisvdg** [gig-tech/terraform-provider-ovc#8]
you never get a clean plan run when using a created cloudspace
~ ovc_cloudspace.cloudspace
resource_limits.%:                         "5" => "3"
resource_limits.max_network_peer_transfer: "-1" => ""
resource_limits.max_num_public_ip:         "-1" => ""

Original issue: https://git.gig.tech/nubera/terraform-provider-ovc/issues/16

**Comment by chrisvdg** [comment]
solution:
you have to set all resource values

Original comment: https://git.gig.tech/nubera/terraform-provider-ovc/issues/16#note_57341

**Comment by chrisvdg** [comment]
See also  https://git.gig.tech/nubera/terraform-provider-ovc/issues/24

Original comment: https://git.gig.tech/nubera/terraform-provider-ovc/issues/16#note_169626

**Comment by chrisvdg** [comment]
Changes needed:
- If not set, just use the defaults of OpenvCloud (== -1)

Original comment: https://git.gig.tech/nubera/terraform-provider-ovc/issues/16#note_220462

**Comment by katia-e** [comment]
The solution is to provide default values of the limits in `variable.tf`
``` sh
variable "max_memory_capacity" {
  description = "maxMemoryCapacity"
  default = "-1"
}

variable "max_disk_capacity"{
  description = "max disk capacity"
  default = "-1"
}

variable "max_cpu_capacity"{
  description = "max cpu capacity"
  default = "-1"
}

variable "max_network_peer_transfer"{
  description = "max network peer transfer"
  default = "-1"
}

variable "max_num_public_ip"{
  description = "max num public IPs"
  default = "-1"
}

```
